package main.java;

import main.java.controls.FlowEditor;
import main.java.structures.DebateEvents;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

public class SaveHandler {
	private final Properties saveProperties = new Properties();
	private final FlowEditor editor;
	private       File       workingFile;

	public SaveHandler(FlowEditor editor, File workingFile) {
		this.editor = editor;
		this.workingFile = workingFile;
	}

	public File getWorkingFile() {
		return workingFile;
	}

	public void save() throws IOException {
		saveProperties.put("Event", editor.debateEventProperty().getValue().getName());
		saveProperties.put("Layout", String.valueOf(editor.currentLayoutProperty().get()));
		editor.getEditorHashMap().forEach((k, v) -> saveProperties.put(k.getName(), v.getHtmlText()));
		saveProperties.store(new FileOutputStream(workingFile), "Save file generated by DebateApp");

		AppUtils.logger.info("Saved to " + workingFile.getAbsolutePath());
	}

	public void open(File file, DebateEvents events) throws IOException {
		workingFile = file;

		AtomicReference<String> event = new AtomicReference<>();
		AtomicReference<Integer> layout = new AtomicReference<>();
		HashMap<String, String> text = new HashMap<>();

		saveProperties.load(new FileInputStream(workingFile));
		saveProperties.forEach((k, v) -> {
			String key = (String) k;
			String value = (String) v;
			switch(key) {
			case "Event":
				event.set(value);
				break;
			case "Layout":
				layout.set(Integer.valueOf(value));
				break;
			default:
				text.put(key, value);
				break;
			}
		});

		editor.currentLayoutProperty().set(layout.get());
		editor.debateEventProperty().set(events.getEvent(event.get()));
		editor.getEditorHashMap().forEach((speech, minimalHTMLEditor) -> minimalHTMLEditor.setHtmlText(text.get(speech.getName())));

		AppUtils.logger.info("Opened " + file);
	}
}